name: Build and push the image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Environment Variables
        run: |
          echo "DOCKERHUB_USERNAME=$(echo ${{ secrets.DOCKERHUB_USERNAME }})" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deploy/Dockerfile
          pull: true
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/blog-drupal:latest
            ${{ env.DOCKERHUB_USERNAME }}/blog-drupal:${{ env.GITHUB_RUN_NUMBER }}
